mysql:
  host: "127.0.0.1"
  port: 3307
  user: "root"
  password: "YOUR_MYSQL_PASSWORD"
  database: "economic_monitoring_db"

world_bank:
  base_url: "https://api.worldbank.org/v2"
  countries:
    - "USA"
    - "KOR"
    - "JPN"
    - "DEU"
  indicators:
    - "NY.GDP.MKTP.CD"
    - "FP.CPI.TOTL"
    - "SL.UEM.TOTL.ZS"
    - "FR.INR.RINR"
    - "NE.EXP.GNFS.CD"
    - "NE.IMP.GNFS.CD"
  per_page: 20000
